---
- name: Load profiles to run
  set_fact:
    profile_values: "{{ lookup('template', 'profiles.yml.j2') }}"

- name: Install K8set
  kubernetes.core.helm:
    name: "{{ release_name }}"
    chart_ref: ../services/k8set/chart
    namespace: "{{ namespace }}"
    create_namespace: yes
    binary_path: "{{ helm_path }}"
    kubeconfig_path: "{{ kubeconfig_path }}"
    state: present
    wait: yes
    values:
      profiles: "{{ profile_values }}"
  tags:
    - skip_ansible_lint
